apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  DB_HOST: mongod-0.mongodb-service.default.svc.cluster.local,mongod-1.mongodb-service.default.svc.cluster.local,mongod-2.mongodb-service.default.svc.cluster.local
  DB_NAME: admin
  DB_PASS: password
  DB_PORT: "27017"
  DB_USER: admin
  HASH_KEY: 78:5f:4d:4e:a8:6a
  MONGO_INITDB_DATABASE: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_INITDB_ROOT_USERNAME: admin
  REDIS_HOST: redis.redis.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_MASTER_PASSWORD: a-very-complex-password-here
  REPLICA_SET: "rs0"