apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: megaserver/backend:v1
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: backend-configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: backend-configmap
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: DB_PASS
                  name: backend-configmap
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: backend-configmap
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: backend-configmap
            - name: HASH_KEY
              valueFrom:
                configMapKeyRef:
                  key: HASH_KEY
                  name: backend-configmap
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: backend-configmap
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: backend-configmap
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: backend-configmap
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: backend-configmap
            - name: REDIS_MASTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_MASTER_PASSWORD
                  name: backend-configmap
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: backend-configmap
            - name: REPLICA_SET
              valueFrom:
                configMapKeyRef:
                  key: REPLICA_SET
                  name: backend-configmap
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          